[package]
name = "pastelogue"
version = "0.1.0"
authors = ["Deseteral <deseteral@gmail.com>"]
edition = "2018"

[dependencies]
kamadak-exif = "0.3"
regex = "1"
serde = "1"
serde_json = "1"
walkdir = "2"
