name: Rust

on: [push]

jobs:
  build:    
    strategy:
      matrix:
        os: [macOS-10.14, windows-2019, ubuntu-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
