name: Build

on: [push]

jobs:
  Build:
    strategy:
      matrix:
        os: [macOS-10.14, windows-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1

    - name: '[MacOS] Setup exiv2'
      if: matrix.os == 'macOS-10.14'
      run: ./scripts/setup_exiv2_macos.sh

    - name: '[Windows] Setup exiv2'
      if: matrix.os == 'windows-latest'
      run: .\scripts\setup_exiv2_windows.ps1

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
