name: Build

on: [push]

jobs:
  Build:
    strategy:
      matrix:
        # os: [macOS-10.14, ubuntu-latest, windows-latest]
        os: [macOS-10.14, ubuntu-latest]
        rust: [stable]
        # rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: '[MacOS] Setup exiv2'
      if: matrix.os == 'macOS-10.14'
      run: ./build/unix.sh && brew install exiv2

    - name: '[Linux] Setup exiv2'
      if: matrix.os == 'ubuntu-latest'
      run: ./build/unix.sh

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
