name: Build

on: [push]

jobs:
  MacOS:
    strategy:
      matrix:
        rust: [stable, nightly]
    runs-on: macOS-10.14
    steps:
    - name: Install gexiv2 from brew
      run: brew update && brew install gexiv2
    - uses: actions/checkout@v1
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust }}
          override: true
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
